name: Comment on new pull request

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
      - canary

jobs:
  comment_on_new_pr:
    name: Comment on new pull request
    runs-on: ubuntu-latest

    steps:
      - name: Generate access token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Add comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { commentOnNewPr } = await import("${{ github.workspace }}/.github/scripts/comment-on-new-pr.js");
            await commentOnNewPr({ context, github });
