name: Quality

on:
  pull_request:
  push:
    branches:
      - "canary"
      - "main"

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: package.json
          check-latest: true

      - run: pnpm install
      - run: pnpm test

      - name: Check linting (Oxlint)
        run: pnpm oxlint:check

      - name: Check linting (ESLint)
        run: pnpm eslint:check

      - name: Check formatting (Prettier)
        run: pnpm prettier:check

      - name: Check linting (ESLint)
        run: pnpm typescript:check
