name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: "I understand that this action will publish everything on canary to the latest tag"
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Merge canary into main
        run: |
          git merge --ff-only origin/canary
          git push
