name: Release via comment

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  release_via_comment:
    name: Release via comment
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      ) &&
      contains(github.event.comment.body, '!release this')

    steps:
      - name: Generate access token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          # Ensure branches share histories; see:
          # https://github.com/actions/checkout/issues/125
          fetch-depth: 0

      - name: Verify PR and dispatch release workflow
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          USER_NAME: ${{ vars.RELEASE_USER_NAME }}
          USER_EMAIL: ${{ vars.RELEASE_USER_EMAIL }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { releaseViaComment } = await import("${{ github.workspace }}/.github/scripts/release-via-comment.js");
            await releaseViaComment({ context, core, exec, github });
