name: Test
on:
  pull_request:
  push:
  workflow_call:

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install
        uses: ./.github/composite-actions/install
        with:
          node-version: ${{ matrix.node }}

      - run: pnpm test
